config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :baskets do
    member do
      get :delivery
      get :order
      post :order_submit
      get :validation
    end
    resources :basket_items, only: [:show]
  end
  resources :products do
    resources :basket_items, only: [:create]
  end
  resources :basket_items, only: [:update, :delete]
  resources :relay_points
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/basket.rb
class Basket < ApplicationRecord
  STATUSES = %w[ pending finished ]

  belongs_to :user
  belongs_to :relay_point, optional: true
  has_many :basket_items, dependent: :destroy
  has_many :products, through: :basket_items

  validates :basket_status, inclusion: { in: STATUSES }

  scope :all_finished,  -> { where(basket_status: "finished") }
  scope :all_pending,   -> { where(basket_status: "pending") }

  def total_price
    basket_items.includes(:product).sum(&:price)
  end
end

app/models/basket_item.rb
class BasketItem < ApplicationRecord
  belongs_to :product
  belongs_to :basket
  # after_commit :maj_qte_product, on:[:create, :update]
  # after_commit :maj_qte_product_back, on:[:destroy]

  def price
    product.pricing * quantity
  end

  def maj_qte_product(qtity)
    self.quantity += qtity.to_i
    save
    product.quantity -= qtity.to_i
    product.save
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :basket_items
    has_one_attached :photo
    validates :name, presence: true
    validates :pricing, presence: true
    validates :category, presence: true

    def save_if_able
      begin
        self.save
      rescue => exception
        puts exception
      end
    end
end

app/models/relay_point.rb
class RelayPoint < ApplicationRecord
    has_many :baskets, dependent: :destroy
    validates :name, presence: true
    validates :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :baskets

  def current_basket
    baskets.all_pending.last || Basket.create(user: self)
  end

  def full_name
    return email unless first_name && last_name

    "#{first_name.capitalize} #{last_name.capitalize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
  before_action :set_basket_item, only: [:update, :destroy]

  def create
    product = Product.find(params[:product_id])
    @basket_item = BasketItem.new(basket_item_params)
    @basket_item.basket = current_user.current_basket
    @basket_item.product = product
    @basket_item.save
    redirect_to products_path #vérifier la page de retour
  end

  def update
    respond_to do |format|
      if @basket_item.maj_qte_product(basket_item_params[:quantity])
        format.html { redirect_to products_path, notice: 'Quantité modifiée' }
        format.json { render json: { basket_price: @basket_item.basket.total_price,
                                     basket_quantity: @basket_item.quantity } }
      else
        format.html { redirect_to products_path, alert: 'La quantité n\a pas pu être modifiée' }
        format.json { render json: { errors: @basket_item.errors.full_messages.join(', ') } }
      end
    end
  end

  def destroy
    @basket_item.destroy
    redirect_to products_path #vérifier la page de retour
  end

  private
  def basket_item_params
    params.require(:basket_item).permit(:quantity)
  end

  def set_basket_item
    @basket_item = BasketItem.find(params[:id])
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :set_basket, only: [:show, :edit, :update, :order, :order_submit, :delivery, :destroy]

  def index
    @baskets = Basket.all
  end

  def new
    @basket = Basket.new
  end

  def create
    @basket = Basket.new(basket_params)
    @basket.save
    redirect_to basket_path(@basket)
  end

  def show
    @basket_items = @basket.basket_items
    destroy_empty_basket_item(@basket_items)
    @products = @basket.products
    @basket_items_by_category = @basket.basket_items.includes(:product).group_by { |bi| bi.product.category }
    nb_items_in_basket = @basket_items.sum(:quantity)
    if nb_items_in_basket <= 1
      @nb_items_in_basket = "#{nb_items_in_basket} produit dans le panier"
    else
      @nb_items_in_basket = "#{nb_items_in_basket} produits dans le panier"
    end

  end

  def edit
  end

  def update
    @basket.update(basket_params)
    redirect_to basket_path(@basket)
  end

  def destroy
    @basket.destroy
    redirect_to baskets_path
  end

  def order
    @basket_items = @basket.basket_items.includes(:product)
    @total_price = calcul_sum(@basket_items)
    @basket_items_by_category = @basket_items.group_by { |bi| bi.product.category }

    @relay_points = RelayPoint.all

  end

  def order_submit
    @basket.basket_status="finished"
    @basket.save

    @basket = Basket.new
    @basket.user_id = current_user.id
    @basket.save
    redirect_to validation_basket_path

  end

  def delivery
  end

  def validation
  end

  private

  def calcul_sum(basket_items)
    sum = 0
    basket_items.each do |bi|
      sum += bi.quantity * bi.product.pricing
    end
    sum
  end

  def destroy_empty_basket_item(basket_items)
      basket_items.each do |item|
        if item.quantity == 0
          item.destroy
        end
      end
  end

  def basket_params
    params.require(:basket).permit(:name, :description,)
  end

  def set_basket
    @basket = Basket.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  before_action :set_user, only: [:dashboard]
  def home
  end

  def dashboard
    @user = current_user
    @current_basket = current_user.current_basket
    @finished_baskets = current_user.baskets.all_finished
  end

  private

  def set_user
    @user = current_user
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @basket_item = BasketItem.new
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @product.destroy
      redirect_to products_path, status: :see_other
    else
      redirect_to products_path, flash[:error] = "Le produit n'a pas pu etre supprimé: #{@product.errors.full_messages.join(', ')}"
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :pricing, :quantity, :category, :photo)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/relay_points_controller.rb
class RelayPointsController < ApplicationController
  before_action :set_relay_point_id, only: [:show, :edit, :update, :destroy]

  def index
    @relay_points = RelayPoint.all
  end

  def new
    @relay_point = RelayPoint.new
  end

  def create
    @relay_point = RelayPoint.new(relay_point_params)
    @relay_point.save
    redirect_to relay_point_path(@relay_point)
  end

  def show
  end

  def edit
  end

  def update
    @relay_point.update(relay_point_params)
    redirect_to relay_point_path(@relay_point)
  end

  def destroy
    @relay_point.destroy
    redirect_to relay_points_path, status: :see_other
  end

  private

  def relay_point_params
    params.require(:relay_point).permit(:name, :description, :address, :zip_code, :city, :country, :phone, :email)
  end

  def set_relay_point_id
    @relay_point = RelayPoint.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/basket_items/edit.html.erb
<h1>BasketItems#edit</h1>
<p>Find me in app/views/basket_items/edit.html.erb</p>

app/views/basket_items/index.html.erb
<h1>BasketItems#index</h1>
<p>Find me in app/views/basket_items/index.html.erb</p>

app/views/basket_items/new.html.erb
<h1>BasketItems#new</h1>
<p>Find me in app/views/basket_items/new.html.erb</p>

app/views/basket_items/show.html.erb
<h1>BasketItems#show</h1>
<p>Find me in app/views/basket_items/show.html.erb</p>

app/views/baskets/edit.html.erb
<h1>Baskets#edit</h1>
<p>Find me in app/views/baskets/edit.html.erb</p>

app/views/baskets/index.html.erb
<h1>Baskets#index</h1>
<p>Find me in app/views/baskets/</p>

app/views/baskets/new.html.erb
<h1>Baskets#new</h1>
<p>Find me in app/views/baskets/new.html.erb</p>

app/views/baskets/order.html.erb
<section class="section__show__order">
  <div class="container-small">
    <h1>Commande</h1>
    <h5 class="show__order__title--wrapper">Livraison</h5>
    <%= render "shared/relay_pointv"%>
    <h5 class="show__order__title--wrapper">Récapitulatif</h5>
    <%= render "shared/paiement"%>
    <h5 class="show__order__title--wrapper">Paiement</h5>
    <%= render "shared/payment_method"%>
    <div class="show__order__btn--wrapper">
      <%= button_to "Valider ma commande", order_submit_basket_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
</section>

app/views/baskets/show.html.erb
<section class="section__show_basket">
  <div class="container-large">
      <%= link_to products_path, class: "decoration-none" do %>
        <span class="btn-return"><i class="fa-solid fa-arrow-left"></i>Retour aux produits</span>
      <% end %>
    <div class="show__basket__wrapper">
      <div class="show__basket__header">
        <div class="basket__header--title">
          <h1>Détail panier</h1>
          <p class="header-3"><%= @nb_items_in_basket %></p>
        </div>
        <div class="show__basket__pricing">
          <h2 class="header-3">Total : <span id="basket-total-price"><%= "%.2f" % (@basket.total_price) %></span>€</h2>
          <%= link_to "Valider mon panier", order_basket_path, class: "btn btn-primary" %>
        </div>
      </div>
      <!-- tableau du panier-->
      <% @basket_items_by_category.each do |category, basket_items| %>
          <details open>
              <summary class="show__basket__summary"><%= category %></summary>
              <table class="show__basket__table">
                  <% basket_items.each do |basket_item| %>
                      <tr class="show__basket__line"
                          data-controller="calcul-tarif"
                          data-calcul-tarif-unit-price-value="<%= basket_item.product.pricing %>"
                          data-calcul-tarif-product-quantity-value="<%= basket_item.product.quantity %>"
                          data-calcul-tarif-update-url-value="<%= basket_item_path(basket_item) %>"
                          data-calcul-tarif-target="line">
                          <td><%= cl_image_tag(basket_item.product.photo.key, width: 50, height: 50, crop: :fill) %></td>
                          <td style="width: 50%"><strong><%= basket_item.product.name %></strong></td>
                          <td style="width: 10%"><%= basket_item.product.pricing %> €</td>
                          <td class="show__basket__table__btn">
                              <button class="table__line__btn--moins" data-action="click->calcul-tarif#calculTarifMoins"><i class="fa-solid fa-circle-minus"></i></button>
                              <input type="number" data-calcul-tarif-target="input" name="qte" min="0" max=<%= basket_item.product.quantity %> value=<%= basket_item.quantity %> class="table__line--qte" >
                              <button class="table__line__btn--plus" data-action="click->calcul-tarif#calculTarifPlus"><i class="fa-solid fa-circle-plus"></i></button>
                          </td>
                          <td style="width: 10%"><p class="table__line__btn--total-tarift"><span data-calcul-tarif-target="fullPrice"><%= "%.2f" % (basket_item.quantity * basket_item.product.pricing) %></span>€</p></td>
                          <td data-action="click->calcul-tarif#delete" style="cursor: pointer;"><i class="fa-solid fa-trash"></i></td>
                      </tr>
                  <% end %>
              </table>
          </details>
      <% end %>
    </div>
  </div>
</section>

app/views/baskets/validation.html.erb
<section class="section__validation">
    <div class="container-small">
      <div class="shadow-lg bg-body modal__validation">
        <p class="section__title">Votre demande de paiement a été<br> enregistrée avec succès<p>
        <%= link_to "Retour à l'accueil", root_path, class: "btn btn-primary" %>
      </div>
    </div>
</section>

<!--
<section class="section__validation_payment">
    <div class="container-large">
        <h1 class="section__validation_payment--title">Votre demande de paiementa été<br> enregistrée avec succès</h1>

        <div class="validation__payement_details">
            <h3>Détails du paiement</h2>
            <hr>
            <div class="validation__payement_details--infos">
                <div class="payement__details_infos--site"><p>Adresse URL:</p><p>https://gaspy.com</p></div>
                <div class="payement__details_infos--site"><p>BOUTIQUE :</p><p>GASPY</p></div>
                <div class="payement__details_infos--site"><p>Identifiant du marchand</p><p>xxxxxx</p></div>
                <div class="payement__details_infos--site"><p>Référence commande :</p><p>qc-77514</p></div>
            </div>
        </div>

        <div class="validation__payement_details">
            <h3>CARTE BANCAIRE : xx EUR</h2>
            <hr>
            <div class="validation__payement_details--infos">
                <div class="payement__details_infos--site"><p>Date / heure:</p><p>https://gaspy.com</p></div>
                <div class="payement__details_infos--site"><p>Numéro de carte :</p><p>xxxxxxxxxxxx0057</p></div>
                <div class="payement__details_infos--site"><p>Numéro d'autorisation :</p><p>3fe4e5</p></div>
                <div class="payement__details_infos--site"><p>Numéro de contrat :</p><p>5786532 011</p></div>
                <div class="payement__details_infos--site"><p>Type :</p><p>DEBIT VADS</p></div>
                <div class="payement__details_infos--site"><p>N° de transaction CB :</p><p>515734</p></div>
                <div class="payement__details_infos--site"><p>Usage :</p><p>Débit</p></div>
            </div>
        </div>
    </div>
    <div class="validation__payement_close"><%= link_to "Retour à l'accueil", root_path, class: "validation__payement_close-btn" %></div>
</section>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gaspy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="padding-global"><%= yield %></div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="d-flex">
  <div class="profile_name">
    <%= current_user.first_name %>
  </div>
  <div class="profile_email">
    <%= current_user.email %>
  </div>
<div class="d-flex jc">
  <div class="profile_address">
    <%= current_user.address %>
    <%= current_user.city %>
    <%= current_user.zip_code %>
  </div>
</div>
</div>
<div class="d-flex jc">
  <div id="curr" class="profile_last_name">
    <%= current_user.last_name %>
  </div>
  <div id="curr" class="profile_phone">
    <%= current_user.phone %>
  </div>
 
</div>

<h1><%= @user.full_name %></h1>

<h2>Mon panier en cours</h2>
<% if @current_basket %>

  <table>
    <thead>
      <tr>
        <th>Produit</th>
        <th>Quantité</th>
        <th>Prix</th>
      </tr>
    </thead>
    <tbody>
    <% @current_basket.basket_items.each do |basket_item| %>
      <tr>
        <td><%= basket_item.product.name %></td>
        <td>x<%= basket_item.quantity %></td>
        <td><%= basket_item.price %> €</td>
      </tr>
    <% end %>
  </tbody>
<% end %>

<% if @finished_baskets %>
  <ul>
    <% @finished_baskets.each do |basket| %>
      <li>
        <%= basket.basket_items.count %> Vos anciens panier
      </li>
    <% end %>
  </ul>
<% end %>

app/views/pages/home.html.erb
<main class="">
  <section class="section__banner">
    <div>
      <h1>Réduisons le gaspillage alimentaire.</h1>
      <p>Ne nous laissons plus submerger par le trop plein de déchets alimentaire. Distribuons au-lieu de jeter.</p>
      <%= link_to "Produits", products_path, class: "btn btn-primary btn-lg btn-hero" %>
    </div>
  </section>
  <div class="container-medium">
    <div class="paragraphe">
      <h2 class="paragraphe__title">Qui sommes nous ?</h2>
      <p>Chaque jour, des aliments frais sont gaspillés dans des commerces, simplement parce qu'ils n'ont pas été vendus à temps. L'application Gaspy permet aux utilisateurs d'acheter des Paniers Surprise composés de produits invendus à petits prix.</p>
    </div>
    <div class="cards">
      <a class="card__home__link" href="#">
        <div class="card__home">
          <div class="card__home__img--wrapper">
            <img class="card__home__img" src="https://images.unsplash.com/photo-1532634896-26909d0d4b89?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80" alt="">
          </div>
            <div class="card__home__content">
              <h3 class="header-5 card__home__title">Le gaspillage</h3>
              <p>Le gaspillage est un fleau qui touche tout le monde sans exception et ce constat est bien triste.</p>
            </div>
        </div>
      </a>
      <a class="card__home__link" href="#">
        <div class="card__home">
          <div class="card__home__img--wrapper">
            <img class="card__home__img" src="https://images.unsplash.com/photo-1546525848-3ce03ca516f6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3570&q=80" alt="">
          </div>
            <div class="card__home__content">
              <h3 class="header-5 card__home__title">Problématique étudiante</h3>
              <p>L'accès à l'alimentation est un problématique réel de plus en plus présente chez les étudiants !</p>
            </div>
        </div>
      </a>
      <a class="card__home__link" href="#">
        <div class="card__home">
          <div class="card__home__img--wrapper">
            <img class="card__home__img" src="https://images.unsplash.com/photo-1578357078586-491adf1aa5ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1364&q=80" alt="">
          </div>
            <div class="card__home__content">
              <h3 class="header-5 card__home__title">Le but de Gaspy</h3>
              <p>Empêcher que de nombreux étudiants ne reste ni le ventre ni le frigo vide, tout en permettant à certains établissements de réduire leur déchets.</p>
            </div>
        </div>
      </a>
    </div>
  </div>
  
  <section>
    <div class="container-large">
      <div class="banner__margin--top">
        <img class="banner__img" src="https://images.unsplash.com/photo-1536919011766-09449b44af40?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80" alt="#">
      </div>
    </div>
  </section>
  
  <section class="">
    <div class="container-medium">
      <div class="paragraphe">
        <h2 class="paragraphe__title">Gaspy</h2>
        <p>Gaspy est une application permettant de réduire le gaspillage alimentaire en proposant des produits invendus à des prix réduits. Nous souhaitons également sensibiliser les étudiants à la problématique du gaspillage alimentaire.</p>
      </div>
      <div class="features">
        <div class="feature__home">
          <div class="feature__home__content">
            <h3 class="header-2">Vous êtes commerçant et vous avez des invendus alimentaires ?</h3>
            <p>Gaspy peut vous permettre de réduire votre gaspillage alimentaire tout en attirant de nouveaux clients et en réduisant vos pertes.</p>
          </div>
          <div class="feature__home__img--wrapper">
            <img class="feature__home__img" src="https://images.unsplash.com/photo-1571512974450-432a728f2897?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3184&q=80" alt="">
          </div>
        </div>
        <div class="feature__home--reverse">
          <div class="feature__home__content">
            <h3 class="header-2">Nos initiatives anti gaspillage</h3>
            <p>Nous travaillons avec les pouvoirs publics, les commerçants et les écoles pour lutter contre le gaspillage alimentaire à tous les niveaux.</p>
          </div>
          <div class="feature__home__img--wrapper">
            <img class="feature__home__img" src="https://images.unsplash.com/photo-1599059813005-11265ba4b4ce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80" alt="">
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>
<%= simple_form_for @product do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :pricing %>
  <%= f.input :quantity %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>

app/views/products/index.html.erb
<section class="section__index__product">
  <div class="container-medium">
   <h1 class="header-2">Produits</h1>
    <div class="cards__products">
      <%= render "shared/card_product" %>
    </div>
  </div>
</section>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>
<%= simple_form_for @product do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :pricing %>
  <%= f.input :quantity %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>

app/views/products/show.html.erb
<section class="section__show__product">
  <div class="container-medium">
    <%= link_to products_path, class: "decoration-none" do %>
      <span class="btn-return"><i class="fa-solid fa-arrow-left"></i>Retour aux produits</span>
    <% end %>
    <h1><%= @product.name %></h1>
    <div class="show__product__content">
      <div class="show__product__infos">
        <div class="show__product__img--wrapper">
          <%= cl_image_tag @product.photo.key, class: "show__product__img" %>
        </div>
        <div class="show__product__infos--top">
          <p><%= @product.quantity %> unité(s) disponible</p>
          <p><%= @product.pricing %>€ / unitée</p>
        </div>
        <div class="divider"></div>
        <h3>Description</h3>
        <p><%= @product.description %></p>
      </div>
      <div class="show__product__wrapper">
      <p class="show__product__tag"><%= @product.category %></p>
        <div class="show__product__form shadow-sm">
          <p class="show__product__pricing"><%= @product.pricing %>€</p>
          <%= simple_form_for([@product, @basket_item]) do |f| %>
            <div class="show__form__input--wrapper">
              <%= f.input :quantity, label: false,
                        wrapper_html: { class: "show__form__input"},
                        input_html: { min: 0, max: @product.quantity } %>
              <%= f.submit 'Ajouter au pannier', class: "btn btn-primary" %>
            </div>
          <% end %>
          <div class="divider"></div>
          <button class="btn btn-primary">Voir le panier</button>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/relay_points/edit.html.erb
<h1>RelayPoints#edit</h1>
<p>Find me in app/views/relay_points/edit.html.erb</p>
<%= simple_form_for @relay_point do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :zip_code %>
  <%= f.input :city %>
  <%= f.input :country, as: :string %>
  <%= f.input :phone %>
  <%= f.input :email %>
  <%= f.submit %>
<% end %>

app/views/relay_points/index.html.erb
<section>
  <div class="container1   col-12">
    <div class="relay_points d-flex">
      <%= render "shared/relay_point" %>
     </div>
  </div>
</section>
<hr>

<%= render "shared/payment_method"%>

app/views/relay_points/new.html.erb
<h1>RelayPoints#new</h1>
<p>Find me in app/views/relay_points/new.html.erb</p>
<%= simple_form_for @relay_point do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :zip_code %>
  <%= f.input :city %>
  <%= f.input :country, as: :string %>
  <%= f.input :phone %>
  <%= f.input :email %>
  <%= f.submit %>
<% end %>

app/views/relay_points/show.html.erb
<h1>RelayPoints#show</h1>
<p>Find me in app/views/relay_points/show.html.erb</p>

app/views/shared/_card_product.html.erb
<% @products.each do |product| %>
  <div class="card__product">
    <div class="card__product__img--wrapper">
      <%= cl_image_tag product.photo.key, class: "card__product__img", width: "100" %>
    </div>
    <div class="card__product__content">
      <div class="card__product__infos">
        <h5><%= product.name %></h5>
        <p class="card__product__price"><%= product.pricing %><sup>€</sup></p>
      </div>
      <div class="divider"></div>
      <p>Quantité disponible : <%= product.quantity %></p>
      <div class="divider"></div>
      <!--<p><%= product.description %></p>-->
      <%= link_to "Voir produit", product_path(product.id), class: "btn btn-primary card__prodcut__btn" %>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_paiement.html.erb
<div class="paiement_address">
    <p class="paiement_address--user">
        <strong>Facturation :</strong>
        <%=current_user.first_name%> <%=current_user.last_name%> - <%=current_user.address%>
    </p>
    <button class="btn btn-primary">Modifier</button>
</div>
<hr>
<div class="paiement_basket">
    <details>
        <summary class="paiement_basket--title mb-4">
            <span>Votre panier</span>
            <span class="paiement_basket--title--ico">Voir détails <i class="fa-solid fa-chevron-down"></i> </span>
        </summary>
        <ol>
            <% @basket_items.each do |item| %>
            <li class="paiement_basket--items"><span><%= item.product.name %></span> <span> <%=  "%.2f" % (item.quantity * item.product.pricing) %> €</span></li>
            <% end %>
        </ol>
    </details>
    <hr>
    <div class="paiement_basket--tarif-panier">
        <span> Total HT :</span> <span><%= @total_price %>€</span>
    </div>
</div>